---
title: "Creating the Narrative"
author: "Robin Lee, Schinria Islam, Steven Hun Lee, Wen Fu"
date: "February 14, 2016"
output: html_document
---
##Why Manufacturing?

###Made In the USA: A Tutorial on Manufacturing in America.  

It is not a surprise that the U.S. economy is the largest in the world—representing 22% of nominal global GDP and 17% of the global GDP. A lesser known fact, however, is that the U.S. has the world’s second largest manufacturer, with an industrial output in 2013 of $2.4 trillion. Our manufacturing sector is composed of diverse industries, including petroleum, steel, automobiles, construction machinery, aerospace, agricultural machinery, telecommunications, chemicals, food processing, consumer goods, mining, and many more. 

##What can we show?

This tutorial is designed to help you gain regional understanding of manufacturing activities by navigating the Commodity Flow Survey (CFS) of 2012, a dataset that emerged through a partnership between the Census Bureau and the Bureau of Transportation Statistics (BTS) as a part of the Economic Census. To help understand the movement of goods, the dataset provides information on commodities shipped, their value, weight, and mode of transportation, as well as the origin and destination of shipments of commodities from manufacturing, mining, wholesale, and selected retail and services establishments.

We hope that communities looking to strengthen their regional manufacturing sectors through collaborative efforts, such as those supported by the Investing in Manufacturing Communities Partnership (IMCP), can use this tutorial, in addition to resources provided by the Economic Development Administration, towards better understanding of their manufacturing industries as they come to those of other states and regions as evidenced by the Commodity Flows Survey.


From exploration of the data, we can get a sense of what kinds of stories that the data can tell us.

##Maps, Barplots, and Histograms! Oh My!
